version: "3.9"
services:
  dev-nsi:
    build: .
    ports:
      - 3000:443
    environment:
      - REACT_APP_NSI_API_URL=https://donsaluste-acs.tristesse.lol
      - NODE_ENV=production
      - PORT=443
      - HTTPS=true
      - SSL_CERT_PATH=/certs/tristesse.crt
      - SSL_KEY_PATH=/certs/tristesse.key
    volumes:
      - /certs/:/certs/
